// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsoZtOnlG9id7ey9vF_gh0kEXJi2NjGGo',
    appId: '1:1036275465121:web:fd27103169af1e1cd529e0',
    messagingSenderId: '1036275465121',
    projectId: 'shuttletrack-1aecf',
    authDomain: 'shuttletrack-1aecf.firebaseapp.com',
    storageBucket: 'shuttletrack-1aecf.firebasestorage.app',
    measurementId: 'G-VWE0NT61QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_Ty7nOQeXu_GmJ23-CLjhhULWlvLSWU',
    appId: '1:1036275465121:android:de43985e1b57c4a9d529e0',
    messagingSenderId: '1036275465121',
    projectId: 'shuttletrack-1aecf',
    storageBucket: 'shuttletrack-1aecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv5dHttSiCtoDdtQrjgG6knOVf8iLbFHM',
    appId: '1:1036275465121:ios:821ce0404e45afa9d529e0',
    messagingSenderId: '1036275465121',
    projectId: 'shuttletrack-1aecf',
    storageBucket: 'shuttletrack-1aecf.firebasestorage.app',
    iosBundleId: 'com.example.shuttletrack',
  );
}
